org.gradle.java.home=/Users/jonathan.bernal/Library/Java/JavaVirtualMachines/corretto-17.0.19/Contents/Home
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true

kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2

android.useAndroidX=true
android.nonTransitiveRClass=true

# Versiones centralizadas
KOTLIN_VERSION=2.0.21
AGP_VERSION=8.5.2
COMPOSE_VERSION=1.7.0
KTOR_VERSION=3.0.1
COROUTINES_VERSION=1.9.0
SERIALIZATION_VERSION=1.7.3
